name: efficient_hat_X2
model_type: efficient_hat_X2
scale: 4
num_gpu: auto
manual_seed: 0
resume_training: False
# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    file_pth: /home/cjrathod/scratch/Paired_imagenet_data.h5
   

  val:
    name: Set14
    type: PairedImageDataset
    file_pth: /home/cjrathod/scratch/paired_val_set14.h5
    io_backend:
      type: disk

  test: 
  name: Set5
  type: PairedImageDataset
  file_pth: /home/cjrathod/scratch/paired_val_set5.h5
      
# Dataloaders
train_dataloader:
  batch_size: 4
  shuffle : True
val_dataloader:
  batch_size: 1
  shuffle: false
# Checkpoints
checkpoint: 
network_g:
  type: HAT_Vmamba
  in_chans: 3
  embed_dims: 96
  hat_depth: [2,2,6,4]
  hat_num_heads: [6,6,6,6]
  window_size: 8
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  mlp_ratio: 2.
  upscale: 4
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'


train:
  epoch: 200
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-5
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [25, 50, 75, 100, 125, 150, 175, 180]
    gamma: 0.5

  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
results: /home/cjrathod/projects/def-mhassanz/cjrathod/Efficient-Hat/results
checkpoint: /home/cjrathod/projects/def-mhassanz/cjrathod/Efficient-Hat/checkpoints
device: cuda
